from __future__ import annotations


AGENT_CATALOG = [
    {
        "id": "orchestrator",
        "name": "主控智能体",
        "short_name": "Orchestrator",
        "description": "理解目标、拆分任务、动态组队并控制总预算。",
        "execution_mode": "online",
        "status": "ready",
        "accent": "#58a6ff",
        "skills": ["route-and-plan", "multi-question-decomposition"],
        "tools": [],
    },
    {
        "id": "router",
        "name": "意图路由智能体",
        "short_name": "Router",
        "description": "识别技术、客服、混合或通用请求，并用确定性规则守住产品安全边界。",
        "execution_mode": "online",
        "status": "ready",
        "accent": "#2f81f7",
        "skills": ["intent-routing"],
        "tools": [],
    },
    {
        "id": "evidence-gap",
        "name": "证据补全智能体",
        "short_name": "Evidence Gap",
        "description": "在证据不足时逐轮只收集一项关键字段，并在补齐后触发重新检索。",
        "execution_mode": "online-on-demand",
        "status": "ready",
        "accent": "#d29922",
        "skills": ["evidence-clarification"],
        "tools": [],
    },
    {
        "id": "general",
        "name": "通用对话智能体",
        "short_name": "General",
        "description": "使用已配置的真实大模型处理不依赖产品手册或客服政策的开放问题。",
        "execution_mode": "online-on-demand",
        "status": "ready",
        "accent": "#a371f7",
        "skills": ["general-dialogue"],
        "tools": [],
    },
    {
        "id": "memory-curator",
        "name": "会话记忆整理智能体",
        "short_name": "Memory Curator",
        "description": "异步整理可追溯摘要，同时保留完整账本、结构化槽位与证据版本。",
        "execution_mode": "online-background",
        "status": "ready",
        "accent": "#39c5cf",
        "skills": ["memory-curation"],
        "tools": [],
    },
    {
        "id": "multimodal",
        "name": "多模态感知智能体",
        "short_name": "Multimodal",
        "description": "提取图片中的文字、产品、部件和可见异常。",
        "execution_mode": "online-on-demand",
        "status": "ready",
        "accent": "#d29922",
        "skills": ["multimodal-inspection"],
        "tools": ["vision.inspect"],
    },
    {
        "id": "knowledge",
        "name": "知识检索智能体",
        "short_name": "Knowledge",
        "description": "执行混合检索、Parent 重排并形成有证据的技术结论。",
        "execution_mode": "online",
        "status": "ready",
        "accent": "#3fb950",
        "skills": ["manual-qa", "troubleshooting"],
        "tools": ["knowledge.search", "knowledge.read", "asset.get"],
    },
    {
        "id": "customer-service",
        "name": "客服业务智能体",
        "short_name": "Customer Service",
        "description": "处理政策、订单槽位、业务查询与人工接管。",
        "execution_mode": "online-on-demand",
        "status": "ready",
        "accent": "#bc8cff",
        "skills": ["customer-policy", "human-handoff"],
        "tools": ["policy.lookup", "order.query", "ticket.create", "handoff.package"],
    },
    {
        "id": "verifier",
        "name": "质量监督智能体",
        "short_name": "Verifier",
        "description": "验证事实、数字、图片、政策和子问题覆盖。",
        "execution_mode": "online",
        "status": "ready",
        "accent": "#f778ba",
        "skills": ["response-verification"],
        "tools": ["verify.claims", "verify.assets"],
    },
    {
        "id": "evolution",
        "name": "离线进化智能体",
        "short_name": "Evolution",
        "description": "分析失败样本、生成候选改进并发起回归评测。",
        "execution_mode": "offline",
        "status": "idle",
        "accent": "#8b949e",
        "skills": [],
        "tools": ["eval.run-suite"],
    },
]
